### ISSUE TITLE
Selecting fill tool in lines mode while working on a vector level chrases the program  

### ISSUE THREAD

**Issue by GabrielCambe** [morevnaproject/opentoonz#3] opened 2018-01-15 18:47 UTC
*creating a toonz raster, raster or scan level makes possible to select the tool but returning to a vector level without changing the mode of the fill tool causes it to crash
*creating a toonz raster level, raster or scan level and changing the mode of the tool from lines to area makes possible to return to the vector level and apparently solves the problem, since doing this makes impossible to recreate the error without closing the scene and opening it again (discarding changes).

I'm on a amd64 Debian Stretch, using Opentoonz 1.2.0.2 morevna edition.

**Comment by morevnaproject** [comment] 2018-01-21 16:21
Duplicate of https://github.com/opentoonz/opentoonz/issues/1737

**Closed by morevnaproject** 2018-01-21 16:21 UTC
